version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - run:
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
          name: Create .terraformrc file locally
      - terraform/fmt:
          path: '~/workspace/environments/devops/iaac/terraform/terraone/live/stage/services/webserver-cluster'
      - terraform/validate:
          path: ~/workspace/environments/devops/iaac/terraform/terraone/live/stage/services/webserver-cluster
      - terraform/init:
          backend: true
          backend_config_file: ~/workspace/environments/devops/iaac/terraform/terraone/live/backend.hcl
          path: ~/workspace/environments/devops/iaac/terraform/terraone/live/stage/services/webserver-cluster
      - terraform/plan:
          backend_config_file: ~/workspace/environments/devops/iaac/terraform/terraone/live/backend.hcl
          path: ~/workspace/environments/devops/iaac/terraform/terraone/live/stage/services/webserver-cluster
      - terraform/apply:
          backend_config_file: ~/workspace/environments/devops/iaac/terraform/terraone/live/backend.hcl
          path: ~/workspace/environments/devops/iaac/terraform/terraone/live/stage/services/webserver-cluster
      # - terraform/destroy:
      #     path: ../live//stage/services/webserver-cluster
    working_directory: ~/workspace/environments/devops/iaac/terraform/terraone/live/stage/services/webserver-cluster
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle