name: Undeploy Web Cluster

on:
  push:
    branches:
      - 'main'

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.push.head.ref }}
      
    - name: Render terraform docs inside the README.md and push changes back to main branch
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: .
        output-file: README.md
        output-method: replace
        config-file: .terraform-docs.yml
        git-push: "false" # if true, it will commit and push the changes

  terraformapply:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    steps:
      # Authenticate to AWS using OIDC
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          # Specify the IAM role to assume
          role-to-assume: arn:aws:iam::377871994725:role/github-actions-role20240305212815987000000001
          aws-region: us-east-1

      - uses: actions/checkout@v3

      # Run Terraform using Hashicorp's setup-terraform Action
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.1
          terraform_wrapper: false
      - name: Apply Terraform configuration
        run: |
          terraform init
          terraform apply --auto-approve