name: Undeploy Web Cluster

on:
  push:
    branches:
      - 'main'

jobs:
  terraformapply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # Authenticate to AWS using OIDC
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          # Specify the IAM role to assume
          role-to-assume: arn:aws:iam::377871994725:role/github-actions-role20240305212815987000000001
          aws-region: us-east-1

      - uses: actions/checkout@v3

      # Run Terraform using Hashicorp's setup-terraform Action
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.1
          terraform_wrapper: false
      - name: Apply Terraform configuration
        run: |
          terraform init
          terraform destroy --auto-approve